# Generated by Django 4.2.3 on 2023-07-19 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_room_reservation_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='room',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
