# Generated by Django 4.2.3 on 2023-07-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0007_alter_student_subject_delete_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
