# Generated by Django 4.2.3 on 2023-07-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0009_subject_remove_student_doctor_remove_student_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
